---
title: "Module 4: Putting it All Together"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Module 4: Putting it together

### Principal components analysis

* [Course materials](4_09_PCA/09_PCA.html)
* [Recitation activities](4_09_PCA/09_PCA_recitation.html)
* Recitation solutions

### Manhattan plots and making lots of plots at once

* [Course materials](4_10_manhattan/10_manhattan.html)
* [Recitation activities](4_10_manhattan/10_manhattan_recitation.html)
* Recitation solutions

### Interactive plots (by Daniel)

* [Course materials](4_11_interactive_plots/11_interactive_plots.html)
* [Recitation activities](4_11_interactive_plots/11_interactive_plots_recitation.html)
* Recitation solutions

### ggplot extension packages and heatmaps

* [Course materials](4_12_leftovers/12_leftovers.html)
* [Recitation activities](4_12_leftovers/12_leftovers_recitation.html)
* Recitation solutions

## [Module 4 Assignment](assignments/module_4.html): due 12/5/23

* Module 4 solutions